### ISSUE TITLE
Security - App running on heroku with DEBUG=True

### ISSUE THREAD

**Issue by fatalaijon** [Hamiz5401/TO-DOZ#112]
I got this error page from your app at 
https://todoz-phukit.herokuapp.com/To-Doz/get_classroom_data?state=h9C2VmfqbG7NujVYMhbshqO93limJd&code=4/0AfgeXvuu7-tlv2oOXsdLcb0R5G88n_dkJyNfsoZSD7sP-lGZF6xrRZWdCEnRHOdtPZV63g&scope=email%20profile%20https://www.googleapis.com/auth/classroom.courses.readonly%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&hd=ku.th&prompt=consent

It shows you are running the app in the cloud with DEBUG=True.
That's a security problem.
[Uploading Warning at _To-Doz_get_classroom_data-20221128.pdf…]()

**Comment by Hamiz5401** [comment]
Change DEBUG to False
