### ISSUE TITLE
Auth Concent Error - https://github.com/Hamiz5401/TO-DOZ/issues/112

### ISSUE THREAD

**Issue by fatalaijon** [Hamiz5401/TO-DOZ#113]
Steps to reproduce:
0. Visit app at https://todoz-phukit.herokuapp.com/
1. Login with Google
2. Click on Add Classroom
3. App redirects to Google consent screen. I check option "View your Classroom Classes" but **not** option to create and edit coursework.
4. Click "Continue"
5. The attached error screen is displayed

This is reproducable.

[To-Doz_Google-Consent-Dialog-20221128.pdf](https://github.com/Hamiz5401/TO-DOZ/files/10099732/To-Doz_Google-Consent-Dialog-20221128.pdf)
[Warning at _To-Doz_get_classroom_data-20221128.pdf](https://github.com/Hamiz5401/TO-DOZ/files/10099733/Warning.at._To-Doz_get_classroom_data-20221128.pdf)

**Comment by Hamiz5401** [comment]
Modified so that if the user doesn't select all scopes or cancel authorization along the way they will be redirected to home page
