### ISSUE TITLE
Cannot add Task

### ISSUE THREAD

**Issue by jbrucker** [Hamiz5401/TO-DOZ#117]
After adding a task to a course, the task is not shown.

1. Add a course (01219245)
2. Click "Add Task" and input values.
3. Click save.
4. The task is not shown.

This is repeatable.  See attached screenshots.
![Todoz-add-task-screen](https://user-images.githubusercontent.com/2336331/204425040-a7f6f789-89c4-42c5-b45d-f0e7227bb3d0.png)
[TO-DOZ-cannot-add-task.pdf](https://github.com/Hamiz5401/TO-DOZ/files/10109263/TO-DOZ-cannot-add-task.pdf)

**Comment by Phukit-Time** [comment]
When you check the `Status ` it will add the task in the history tap, we have rename it to be more meaningful.
