### ISSUE TITLE
"Priority" and "status" are meaningless checkboxes

### ISSUE THREAD

**Issue by jbrucker** [Hamiz5401/TO-DOZ#118]
In the Add Todo dialog I think there are several problems.
1. Priority is just a checkbox.  People expect "priority" to be a level, like High, Medium, or Low
2. Status is just a checkbox. It should have some meaning such as Not Started, Started, Done.
3. When scrolling the window, the input area overlaps the title area.
![Uploading Todoz-add-task-screen.png…]()

**Comment by Phukit-Time** [comment]
We changed the word priority to `High Priority` now, this feature we want user to be able to prioritize some tasks.
We rename Status checkbox to Done now, and send the title area back to background.
