### ISSUE TITLE
App requires unacceptable Permissions grant from Google

### ISSUE THREAD

**Issue by jbrucker** [Hamiz5401/TO-DOZ#120]
The app requires users to consent to "See, create and edit coursework items including assignments, questions, and grades"

Why do you require edit access?  A student cannot create assignments, questions, or grades in a course.  Many people, including me, will not agree to this permission request and your app fails without it.

**Comment by Hamiz5401** [comment]
We changed the scope but for some users who already give us the "See, create and edit coursework items including assignments, questions, and grades" have to remove thier access to To-Doz and try to add classroom data again.
![image](https://user-images.githubusercontent.com/92782075/204558255-520ca319-15f1-42a0-9b65-c75fd5cb48e5.png)
After they remove access and try again they will be redirected to authorization page.
![image](https://user-images.githubusercontent.com/92782075/204559289-0c9605eb-7e29-404f-a936-30fc8f59ccde.png)
