### ISSUE TITLE
User stories 1-3 doesn't seem like user stories

### ISSUE THREAD

**Issue by GToidZ** [Hamiz5401/TO-DOZ#2]
There are some confusions in your user stories:

* Firstly, the three stories doesn't seem to come from a user perspective. User stories should be you guys *impersonating* users.
* Editing and deleting Tasks might be requirements for your project more than user stories, users already know that they should also be able to edit or delete their own Tasks if they can create them.
* The **Then(s)** should be final end results of user interaction, showing pages for user to do what they needed are actually considered a **When**.

**Comment by koakatta** [comment]
change persona, criteria in story 1
replace story 2,3 with a new story
added story 6 (new)
